baseurl = "http://localhost"
languageCode = "en-us"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0) License."
title = "Rick Cogley Central"
disqusShortname = "rickcogley" # Optional, enable Disqus integration
MetaDataFormat = "toml"
# theme = "hyde-x"
theme = "redlounge"
paginate = 5

[author]
    name = "Rick Cogley"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/:section/:slug"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"


#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # Used when a given page doesn't set its own.
    defaultDescription = "A post by Rick Cogley"
    defaultKeywords = "cogley,post"
    
    categoriescss = "/css/categories.css"

    sidebartitle = "Rick Cogley Central"
    sidebartagline = "create > consume"

    postsblurb = "Wherein we chronologically list pithy-yet-informative articles on tech, productivity, Japan, business and whatever else strikes our fancy."


    [[menu.main]]
        name = "BlogCogley"
        url = "/post"

    [[menu.main]]
        name = "About"
        url = "/about"    

    [[menu.social]]
        pre = "<i class='fa fa-twitter'></i>"
        url = "http://www.twitter.com/rickcogley"
        identifier = "twitter"
        weight = 1

    [[menu.social]]
        pre = "<i class='fa fa-google-plus'></i>"
        url = "https://plus.google.com/+RickCogley?rel=author"
        identifier = "google-plus"
        weight = 2

    [[menu.social]]
        pre = "<i class='fa fa-facebook'></i>"
        url = "https://www.facebook.com/rickcogley"
        identifier = "facebook"
        weight = 3

    [[menu.social]]
        pre = "<i class='fa fa-linkedin-square'></i>"
        url = "http://www.linkedin.com/in/rickcogley"
        identifier = "linkedin"
        weight = 4 

    [[menu.social]]
        pre = "<i class='fa fa-camera-retro'></i>"
        url = "http://500px.com/rickcogley"
        identifier = "500px" 
        weight = 5

    [[menu.social]]
        pre = "<i class='fa fa-flickr'></i>"
        url = "http://www.flickr.com/photos/rickcogley/"
        identifier = "flickr"
        weight = 6

    [[menu.social]]
        pre = "<i class='fa fa-vimeo-square'></i>"
        url = "https://vimeo.com/rickcogley"
        identifier = "vimeo" 
        weight = 7

    [[menu.social]]
        pre = "<i class='fa fa-youtube'></i>"
        url = "http://www.youtube.com/user/rickcogley?sub_confirmation=1"
        identifier = "youtube"
        weight = 8  

    [[menu.social]]
        pre = "<i class='fa fa-adn'></i>"
        url = "https://alpha.app.net/rickcogley"
        identifier = "app dot net"
        weight = 9

    [[menu.social]]
        pre = "<i class='fa fa-github'></i>"
        url = "https://github.com/RickCogley"
        identifier = "github"
        weight = 10

    [[menu.social]]
        pre = "<i class='fa fa-thumb-tack'></i>"
        url = "https://pinboard.in/u:rickcogley"
        identifier = "pinboard"
        weight = 11

    [[menu.footer]]
        name = "BlogCogley"
        url = "/post"

    [[menu.footer]]
        name = "eSolia Inc"
        url = "http://esolia.com"



    # Metadata used to drive integrations.
    googleAuthorship = "+RickCogley"
    googleAnalytics = "UA-1040233-5"
    gravatarHash = "42f19a567cf937b98d2ab4cc09918461"

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/rickcogley"
    linkedin = "http://www.linkedin.com/in/rickcogley"
    googleplus = "https://plus.google.com/+RickCogley/posts"
    facebook = "https://www.facebook.com/rickcogley"
    twitter = "https://twitter.com/rickcogley"